name: Feature Request New
description: I have a suggested feature enhancement to the CDM.
labels: 'feature'
body:
  - type: textarea
    attributes:
      label: Background
      description: Please provide the business context of the Issue i.e. what is required and why.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposal
      description: Please put details of the proposed changes in here, Splitting the changes into sections will improve comprehension of the proposal.
                  Use graphics where possible e.g. before/after pictures of the model enhancements
    validations:
      required: true
  - type: textarea
    attributes:
      label: Compatibility
      description: If known, please describe any compatibility issues that this change may have 
                  with existing versions. Please review the list of backwardly incompatible
                  changes and in the design principles for assistance.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ### Any Issue must (Please make sure all boxes are ticked before submitting)
        
        - [ ] include the source of the Issue i.e. is it from the Roadmap, from a Working Group recommendation, github discussions etc
        - [ ] describe the scope of the change, work item or deliverable
        - [ ] be written in “plain English” i.e. try not to use niche business or technical terminology
        ...
