name: Bug request
about: bug request
labels: 'bug'
assignees: []
title: bug change to cdb
body:
  - type: textarea
    attributes:
      label: 'Describe the Issue'
      description: 'A clear and concise description of the issue you encountered.'
    validations:
      required: true
