name: Bug request
about: bug
labels: 'bug'
assignees: []
title: Proposed change to the CDMs
body:
  - type: markdown
    attributes:
      value: 'NOTE: If you want to become an author on freeCodeCamp, you can find everything here: https://www.freecodecamp.org/news/developer-news-style-guide'
  - type: markdown
    attributes:
      value: 'If you are reporting an issue with an article on our news publication, please follow this link to send an email to our editorial team https://mailxto.com/lkj5n7'
  - type: textarea
    attributes:
      label: 'Describe the Issue'
      description: 'A clear and concise description of the issue you encountered.'
    validations:
      required: true
