name: Auto Label Issues

on:
  issues:
    types: [opened]  # Trigger when an issue is opened

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Add label to the issue
        uses: actions/labeler@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'bug'  # Replace with the label you want to auto-assign
